### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by jerps** [ChrisHird/intERPrise#10]
Hi,

Out of curiosity i was looking at the sources.

The use of many comment lines like
// ========================================================

is not really helping to read these sources.
It's really distracting.
I understand the use of these comments when a large program is printed on green-bar paper like in the old days. But these days we don't have these thick green-bar print-outs anymore.

I would suggest placing blank lines at appropriate places to delimit sections of the source.
It's so much easier for the eyes.

**Comment by AtkinsTommy** [comment]
On the contrary, if using RDi with the green on black setting (most restful for the eyes) set comments to red and these lines then stand out and are easier when reading the code.

**Comment by jeffersonvaughn** [comment]
i second the white space vs comment suggestion

**Comment by ChrisHird** [comment]
Your comments are noted. Its a personal choice and not one we can dictate to the community for any submissions. A simple find and replace will fix the problem for anyone who dislikes this style, so this is something we leave up to the contributor to decide.
