### ISSUE TITLE
RPG Fully Free

### ISSUE THREAD

**Issue by AlexKrashevsky** [ChrisHird/intERPrise#11]
I've noticed that many RPG source members in the repository (if not all of them) were developed with h-specs, d-specs and p-specs. 

What's the project team's take on making it a standard to develop RPG in fully free form exclusively (**free)?

**Comment by BobGenis** [comment]
One vote for fully free.

**Comment by Mbogo33** [comment]
As this issue has already received MUCH attention in https://github.com/ChrisHird/intERPrise/issues/4 and a decision has been taken, this discussion is a duplicate.
