### ISSUE TITLE
Convert all code to free format

### ISSUE THREAD

**Issue by WorksOfLiam** [ChrisHird/intERPrise#4]

**Comment by Mbogo33** [comment]
Everything that is sensible, is free format. We prefer neat, structured code and do not enjoy free format D-specs for our contributions. However, that is a preference that each developer can **CHOOSE** how they want to approach that. Certain standards we will not be dogmatic about, others we have quite strong views on.

**Comment by WorksOfLiam** [comment]
@Mbogo33 

Thanks for your response. What is it you don't like about free-format d-specs? Do you not feel like using free-format will make it more maintainable and easier for others to pick up in the future?

Liam Barry

**Comment by chukShirley** [comment]
A one-time conversion could be relatively simple with the JCRHFD command (http://www.jcrcmds.com). I've used it before with good results.

**Comment by Mbogo33** [comment]
All

Please note that TEMBO took a DELIBERATE decision based on experience and fact, on why we prefer fixed form D-specs:
It is more concise (read shorter), by definition clearer as you are "forced" into a specific construct. The biggest benefit though, is that free format declerations can be done anywhere, which is a recipe for heartache. 
If ALL free form declerations are done UPFRONT, it obviously works, but we PREFER fixed form declerations.

Perhaps the following code snippets will demonstrate what we are saying:
http://static.adsero-optima.com/assets/FILEA_B0.RPGLE.txt
http://static.adsero-optima.com/assets/FILEA_B1.RPGLE.txt

It is an **IDENTICAL** trigger program, one being fully free, the other partially free.

It is therefor important that all acknowledge this is our (AO/TEMBO) own standard and that it our choice based on our experience. We however are discussing this issue within the "committee" and will make a decision that is best for the project.

**Comment by ericjooka** [comment]
I second Liam's request. It seems to be a little backward looking if we are stuck in fixed-format anything, let alone D-specs. If we are open sourcing RPG code, we should be showing its modern face. While some of us legacy RPG coders understand fixed format, it will add confusion to the conversation for anyone new, and more than likely have people walk/run away from that. 

It should be much easier to upgrade our own skills and code to modern RPG and avoid personal preferences that keep us coding like it is 1999..

**Comment by ChrisHird** [comment]
At what release did IBM introduce support for free format D specs? I know they have constantly improved support for free format so not being an RPG programmer I am not aware of what came when and what release level IBM pushed support back to? We want this to be supported on the earliest release possible so where do we draw the line and what OS level do we state as the minimum?

**Comment by ericjooka** [comment]
IBM i 7.1 TR 7 - October 8, 2013. Fully free format RPG was announced.

**Comment by ChrisHird** [comment]
Thanks

**Comment by aaronbartell** [comment]
>The biggest benefit though, is that free format declerations can be done anywhere, which is a recipe for heartache.

Almost sounds like you need an RPG linter if the concern is messy code.  Also, a coding standards doc for community contributions.  

I agree it's shorter to do fixed D-specs (I actually prefer them), but I also agree it seems backward to continue using them; especially as the hope is that the next generation adopts this work.

**Comment by ChrisHird** [comment]
The decision has been taken to move to *FREE for all code submissions. 

IBM has offered to consider extending the current (120day) trial for anyone who is making substantial code input to the intERPrise Open Source initiative. This will be done on a case by case basis and we have no control over that decision. 
The alternative for those willing to participate will be to look at the kind offer made for MiWorkplace, again the free license will be based on your contribution to this project. There are other alternatives out there which might also be of use which you should consider using but the main recommendation for IBM I development will be RDi based on its complete tool set such as Git integration etc. 
The code will be updated to reflect this in the near future.
