### ISSUE TITLE
Terminlogy standards

### ISSUE THREAD

**Issue by dhfreinkel** [ChrisHird/intERPrise#8]
I would like to recommend that the use of British English terminology be changed to use the more common terminology that is used and known world wide.

Examples: 
Debtors - Accounts Receivables or Receivables
Creditors - Accounts Payable or Payables
Cash Book - Cash Management.

Depending on the tools being used, and this is probably needed for internationalization and multiple languages, all text/labels should be soft and stored in a repository to make language selection easy. This would then be used to display whichever s appropriate in the environment used example switching between debtors and receivable.

To be able to do this, the system should be set up for DBCS.

**Comment by ChrisHird** [comment]
We are addressing this as we develop the code. The Transport services has already been structured to allow language elements to be isolated and converted to other languages.
